mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: org.example.mybatisplustest.mybatis.entity
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://35.212.162.201:3306/springsecurity_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: remoteuser
    password: Gs5KXwy90mRKuIC
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: 123123
