mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: org.example.mybatisplustest.mybatis.entity
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://35.208.150.98:3306/springsecurity_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: remoteuser
    password: apLeXJ78wrQlMZUBNPBZ
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: 123123
  redis:
    host: 35.208.150.98
    port: 6379
